name: .NET

on:
  push:
    # Publish `main`
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://nuget.pkg.github.com/Bullabs/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release --output artifacts
    - name: Push
      run: dotnet nuget push artifacts/*.nupkg --no-symbols true
    

    

