name: .NET

on:
  release:
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Pack
      run: dotnet pack --configuration Release --output artifacts
    - name: Push
      run: dotnet nuget push artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --no-symbols true --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
