name: .NET

on:
  push:

  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        source-url: https://nuget.pkg.github.com/Bullabs/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: SonarCloud Scan
      uses: Hobbs1210/dotnet-sonarscanner
      with:
        buildCommand: dotnet build .
        projectKey: Bullabs_Qitar
        projectName: Qitar
        sonarOrganisation: bullabs
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}  
